apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app4

resources:
  - ../../base

patches:
  - target:
      kind: Cluster
      name: pg-cluster
    patch: |
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: pg-cluster
        instances: 5
