apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app3-ahmedtest

resources:
  - ../../base
  - namespace.yaml

patches:
  - target:
      kind: Cluster
      name: pg-cluster-ha
    patch: |
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: pg-cluster-ha-nexadd
      spec:
        instances: 5
