apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
namespace: app2-anas
resources:
  - ../../base/cnpg-ha.yaml
patches:
  - target:
      kind: Cluster
      name: pg-cluster-ha
    patch: |-
      spec:
        instances: 3