apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app1-ahmed

resources:
  - cnpg-ha.yaml   # copy of base inside overlay folder

patches:
  - target:
      kind: Cluster
      name: pg-cluster-ha
    patch: |
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: pg-cluster-ha
      spec:
        instances: 1